/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Swathi
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    boolean turn = false; //false means X and true means O
    
    public TicTacToe() {
        initComponents();
        player.setText("X's Turn");
    }
    
    void newturn(boolean turn){
        if (turn == false){
            player.setText("X's Turn");
        }
        else{
            player.setText("O's Turn");
        }
    }
    
    void check(){
        String one = box1.getText();
        String two = box2.getText();
        String three = box3.getText();
        String four = box4.getText();
        String five = box5.getText();
        String six = box6.getText();
        String seven = box7.getText();
        String eight = box8.getText();
        String nine = box9.getText();
        
        if(one == "X" && two == "X" && three == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(four == "X" && five == "X" && six == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(seven == "X" && eight == "X" && nine == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(one == "X" && four == "X" && seven == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(two == "X" && five == "X" && eight == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(three == "X" && six == "X" && nine == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(one == "X" && five == "X" && nine == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(three == "X" && five == "X" && seven == "X"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        
        
        if(one == "O" && two == "O" && three == "O"){
            JOptionPane.showMessageDialog(null, "O Wins!");
        }
        else if(four == "O" && five == "O" && six == "O"){
            JOptionPane.showMessageDialog(null, "O Wins!");
        }
        else if(seven == "O" && eight == "O" && nine == "O"){
            JOptionPane.showMessageDialog(null, "O Wins!");
        }
        else if(one == "O" && four == "O" && seven == "O"){
            JOptionPane.showMessageDialog(null, "O Wins!");
        }
        else if(two == "O" && five == "O" && eight == "O"){
            JOptionPane.showMessageDialog(null, "O Wins!");
        }
        else if(three == "O" && six == "O" && nine == "O"){
            JOptionPane.showMessageDialog(null, "O Wins!");
        }
        else if(one == "O" && five == "O" && nine == "O"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
        else if(three == "O" && five == "O" && seven == "O"){
            JOptionPane.showMessageDialog(null, "X Wins!");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box4 = new javax.swing.JButton();
        box7 = new javax.swing.JButton();
        box2 = new javax.swing.JButton();
        box3 = new javax.swing.JButton();
        box1 = new javax.swing.JButton();
        box5 = new javax.swing.JButton();
        box6 = new javax.swing.JButton();
        box8 = new javax.swing.JButton();
        box9 = new javax.swing.JButton();
        player = new javax.swing.JTextField();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 750));

        box4.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        box7.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });

        box2.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box3.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        box1.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box5.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box6.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });

        box8.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });

        box9.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        box9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box9ActionPerformed(evt);
            }
        });

        player.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        player.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clear.setText("Clear Game");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(player, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(clear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box4.setText("X");
            box4.setForeground(Color.red);
        }
        else{
            box4.setText("O");
            box4.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box4ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box7.setText("X");
            box7.setForeground(Color.red);
        }
        else{
            box7.setText("O");
            box7.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box7ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box2.setText("X");
            box2.setForeground(Color.red);
        }
        else{
            box2.setText("O");
            box2.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box2ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box3.setText("X");
            box3.setForeground(Color.red);
        }
        else{
            box3.setText("O");
            box3.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box3ActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box1.setText("X");
            box1.setForeground(Color.red);
        }
        else{
            box1.setText("O");
            box1.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box1ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box5.setText("X");
            box5.setForeground(Color.red);
        }
        else{
            box5.setText("O");
            box5.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box5ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box6.setText("X");
            box6.setForeground(Color.red);
        }
        else{
            box6.setText("O");
            box6.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box6ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box8.setText("X");
            box8.setForeground(Color.red);
        }
        else{
            box8.setText("O");
            box8.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box8ActionPerformed

    private void box9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box9ActionPerformed
        // TODO add your handling code here:
        newturn(!turn);
        if (turn == false){
            box9.setText("X");
            box9.setForeground(Color.red);
        }
        else{
            box9.setText("O");
            box9.setForeground(Color.blue);
        }
        turn = !turn;
        check();
    }//GEN-LAST:event_box9ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        box1.setText(" ");
        box2.setText(" ");
        box3.setText(" ");
        box4.setText(" ");
        box5.setText(" ");
        box6.setText(" ");
        box7.setText(" ");
        box8.setText(" ");
        box9.setText(" ");
        turn = false;
        newturn(turn);
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton box1;
    private javax.swing.JButton box2;
    private javax.swing.JButton box3;
    private javax.swing.JButton box4;
    private javax.swing.JButton box5;
    private javax.swing.JButton box6;
    private javax.swing.JButton box7;
    private javax.swing.JButton box8;
    private javax.swing.JButton box9;
    private javax.swing.JButton clear;
    private javax.swing.JTextField player;
    // End of variables declaration//GEN-END:variables
}
